model_config:
  visual_bert:
    num_labels: 8000
    training_head_type: classification
    losses:
    - type: logit_bce


dataset_config:
  textvqa:
    use_ocr: false
    use_ocr_info: false
    use_order_vectors: false
    processors:
      # Stop fasttext from loading by overriding the context_processor
      context_processor:
        type: simple_word
        params: {}
      text_processor:
        type: bert_tokenizer
        params:
          tokenizer_config:
            type: bert-base-uncased
            params:
              do_lower_case: true
          mask_probability: 0
          max_seq_length: 128

optimizer:
  type: adam_w
  params:
    lr: 5e-5
    eps: 1e-8

evaluation:
  metrics:
  - textvqa_accuracy

scheduler:
  type: warmup_linear
  params:
    num_warmup_steps: 2000
    num_training_steps: 30000

training:
    lr_scheduler: true
    batch_size: 480
    num_workers: 4
    early_stop:
      criteria: textvqa/textvqa_accuracy
      minimize: false
      patience: 3000
